apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app
    spec:
      containers:
      - image: registryf1.azurecr.io/aksdemo/angular-dotnet:v1
        name: angular-app
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8000
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: angular-app
  labels:
    run: my-app
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8000  # The port you want to expose externally
      targetPort: 8000  # The port your application is listening on
  type: loadbalencer  # Or LoadBalancer depending on your requirements

